import React, { useState, useRef } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, GitCompare, Mail, Download, ShieldCheck, Upload, FolderOpen, ChevronDown } from 'lucide-react';
import { useContractDiff } from '@/hooks/useContractDiff';
import { MetricDeltaStrip } from '@/components/features/diff/MetricDeltaStrip';
import { DualColumnRedline } from '@/components/features/diff/DualColumnRedline';
import { Button } from '@/components/ui/Button';

const VERSION_PRESETS = [
  {
    id: 'lease',
    label: '🏠 Residential Lease',
    v1: 'Standard Model Lease (v1.0)',
    v2: 'Proposed Landlord Draft (v2.1)',
  },
  {
    id: 'msa',
    label: '📄 Freelancer MSA',
    v1: 'Original MSA (v1.0)',
    v2: 'Client Revised MSA (v2.0)',
  },
];

export const ComparePage: React.FC = () => {
  const {
    diffData,
    isLoading,
    activeFilter,
    isSyncScrollLocked,
    selectedDiffClauseId,
    filteredClauses,
    setFilter,
    toggleSync,
    selectDiffClause,
  } = useContractDiff();

  const [selectedPreset, setSelectedPreset] = useState('lease');
  const [customV1Name, setCustomV1Name] = useState('');
  const [customV2Name, setCustomV2Name] = useState('');
  const [showUploadZone, setShowUploadZone] = useState(false);
  const v1InputRef = useRef<HTMLInputElement>(null);
  const v2InputRef = useRef<HTMLInputElement>(null);

  const currentPreset = VERSION_PRESETS.find((p) => p.id === selectedPreset);

  const handleDraftEmail = () => {
    const emailContent = `Subject: Proposed Revisions to ${currentPreset?.v2 || 'Contract'}

Dear Counterparty,

Upon careful review of your draft using LexiAssist AI, we propose the following amendments:

1. Section 6.2 (Security Deposit): Restrict return timeline to 14 days per applicable statute and eliminate non-standard cleaning surcharges.

2. Section 12.2 (Automatic Renewal): Convert automatic multi-year renewal to a month-to-month arrangement with 30-day notice either party.

3. Section 14.1 (Indemnification): Restore mutual indemnification framework — the current one-sided clause creates unacceptable exposure.

We believe these changes bring the agreement into standard market practice and protect both parties equitably.

Please confirm acceptance of these amendments at your earliest convenience.

Best regards`;

    const blob = new Blob([emailContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'Counter_Offer_Letter_Draft.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleExportRedline = () => {
    if (!diffData) return;
    const report = `# Contract Redline Comparison Report
Prepared by LexiAssist AI

## Comparison Summary
- Version A: ${currentPreset?.v1 || 'Original Version'}
- Version B: ${currentPreset?.v2 || 'Revised Version'}

## Risk Score Delta: ${diffData.riskScoreDelta > 0 ? '+' : ''}${diffData.riskScoreDelta} points

## Material Alterations: ${diffData.materialAlterationsCount}
## New Liabilities Added: ${diffData.newLiabilitiesCount}
## Omitted Protections: ${diffData.omittedProtectionsCount}

---
*Generated by LexiAssist AI. Not certified legal counsel.*`;
    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'LexiAssist_Redline_Report.md';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
      {/* Top Header & Breadcrumb */}
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <Link to="/dashboard">
            <Button size="sm" variant="outline" className="text-xs">
              <ArrowLeft className="w-3.5 h-3.5 mr-1" />
              <span>Back to Workspace</span>
            </Button>
          </Link>

          <div>
            <div className="flex items-center gap-2 text-xs text-slate-500 font-mono">
              <span>{customV1Name || currentPreset?.v1}</span>
              <span>vs.</span>
              <span className="text-risk-high font-bold">
                {customV2Name || currentPreset?.v2}
              </span>
            </div>
            <h1 className="text-xl font-bold font-headline text-primary">
              Side-by-Side Contract Comparison & Semantic Diff
            </h1>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2">
          <Button size="sm" variant="outline" onClick={handleDraftEmail} className="text-xs">
            <Mail className="w-3.5 h-3.5 mr-1 text-slate-500" />
            <span>Draft Counter-Offer Letter</span>
          </Button>
          <Button size="sm" variant="brand" onClick={handleExportRedline} className="text-xs font-semibold">
            <Download className="w-3.5 h-3.5 mr-1" />
            <span>Export Redline Report</span>
          </Button>
        </div>
      </div>

      {/* Version Switcher Panel */}
      <div className="bg-surface-light border border-border-light rounded-xl p-4 space-y-4">
        <div className="flex items-center justify-between">
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">
            Comparison Pair
          </p>
          <button
            onClick={() => setShowUploadZone(!showUploadZone)}
            className="text-xs text-brand hover:underline flex items-center gap-1 font-semibold"
          >
            <Upload className="w-3 h-3" />
            {showUploadZone ? 'Use preset versions' : 'Upload custom versions'}
          </button>
        </div>

        {!showUploadZone ? (
          /* Preset version selector */
          <div className="flex flex-wrap gap-2">
            {VERSION_PRESETS.map((preset) => (
              <button
                key={preset.id}
                onClick={() => setSelectedPreset(preset.id)}
                className={`px-4 py-2.5 rounded-lg border text-xs font-semibold transition-all ${
                  selectedPreset === preset.id
                    ? 'bg-primary text-white border-primary shadow-sm'
                    : 'bg-slate-50 text-slate-700 border-slate-200 hover:border-slate-400'
                }`}
              >
                {preset.label}
                <span className="block text-[10px] font-normal opacity-70 mt-0.5">
                  {preset.v1} vs {preset.v2}
                </span>
              </button>
            ))}
          </div>
        ) : (
          /* Custom dual-file upload zone */
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Version 1 Upload */}
            <div className="space-y-2">
              <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
                Version 1 — Original Draft
              </label>
              <input ref={v1InputRef} type="file" accept=".txt,.md,.pdf" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) setCustomV1Name(f.name); }} />
              <button
                onClick={() => v1InputRef.current?.click()}
                className={`w-full flex items-center gap-2 px-3 py-3 rounded-lg border-2 border-dashed transition-all text-left ${
                  customV1Name
                    ? 'border-emerald-400 bg-emerald-50 text-emerald-800'
                    : 'border-slate-200 hover:border-brand text-slate-500 hover:text-brand'
                }`}
              >
                <FolderOpen className="w-4 h-4 flex-shrink-0" />
                <span className="text-xs font-medium truncate">
                  {customV1Name || 'Click to upload Version 1 (.txt, .md, .pdf)'}
                </span>
              </button>
            </div>

            {/* Version 2 Upload */}
            <div className="space-y-2">
              <label className="text-[11px] font-bold text-slate-500 uppercase tracking-wider block">
                Version 2 — Counter-Proposal / Revision
              </label>
              <input ref={v2InputRef} type="file" accept=".txt,.md,.pdf" className="hidden" onChange={(e) => { const f = e.target.files?.[0]; if (f) setCustomV2Name(f.name); }} />
              <button
                onClick={() => v2InputRef.current?.click()}
                className={`w-full flex items-center gap-2 px-3 py-3 rounded-lg border-2 border-dashed transition-all text-left ${
                  customV2Name
                    ? 'border-emerald-400 bg-emerald-50 text-emerald-800'
                    : 'border-slate-200 hover:border-risk-high text-slate-500 hover:text-risk-high'
                }`}
              >
                <FolderOpen className="w-4 h-4 flex-shrink-0" />
                <span className="text-xs font-medium truncate">
                  {customV2Name || 'Click to upload Version 2 (.txt, .md, .pdf)'}
                </span>
              </button>
            </div>

            {customV1Name && customV2Name && (
              <div className="sm:col-span-2">
                <Button variant="primary" size="sm" className="text-xs font-semibold w-full">
                  <GitCompare className="w-3.5 h-3.5 mr-1.5" />
                  Run Semantic Diff on Custom Versions
                </Button>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Metric Delta Strip */}
      {diffData && (
        <MetricDeltaStrip
          materialAlterationsCount={diffData.materialAlterationsCount}
          newLiabilitiesCount={diffData.newLiabilitiesCount}
          omittedProtectionsCount={diffData.omittedProtectionsCount}
          riskScoreDelta={diffData.riskScoreDelta}
          activeFilter={activeFilter}
          onFilterChange={setFilter}
          isSyncScrollLocked={isSyncScrollLocked}
          onToggleSyncScroll={toggleSync}
        />
      )}

      {/* Dual Column Synchronized Redline Viewer */}
      <DualColumnRedline
        clauses={filteredClauses}
        selectedDiffClauseId={selectedDiffClauseId}
        onSelectDiffClause={selectDiffClause}
        isSyncScrollLocked={isSyncScrollLocked}
      />
    </div>
  );
};

